---
title: "Publications"
---

```{js, echo=FALSE}
$(document).ready(function(){
    var content = $('#quarto-content');
    content.find('a[href$=".pdf"]').attr('target', '_blank');
    content.find('a[href^="http://"], a[href^="https://"]')
      .not('a[href*="robcavanaugh.com"]')
      .attr('target', '_blank');
});
```

```{r, include=FALSE}
library(magrittr)
source("R/cv_printing_functions_website.r")

CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1B2gc55CwWn0QidoLk3aqWXFaKGFXqekKV94LVyY7Gug/edit?usp=sharing",
  pdf_mode = 'false'
)
CV$entries_data$institution[CV$entries_data$institution=="N/A"] <- ""
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(stringr)
library(reactable)

t <- CV$entries_data %>%
  dplyr::filter(section == "publications", in_website == "TRUE") %>%
  dplyr::mutate(start = ifelse(start == "N/A", NA, start)) %>%
  fill(start) %>%
  rowwise() %>%
  mutate(
    pdf = ifelse(loc == "N/A", "", glue::glue('<a href="images/{loc}" target="_blank"><button class="btn btn-sm btn-outline-secondary">Author PDF</button></a>')),
    citation = paste(title, pdf),
    year = as.integer(start)
  ) %>%
  ungroup() %>%
  select(Year = year, Article = citation)

reactable(
  t,
  columns = list(
    Year = colDef(width = 80, align = "center"),
    Article = colDef(html = TRUE)
  ),
  striped = TRUE,
  highlight = TRUE,
  bordered = FALSE,
  defaultPageSize = 10,
  defaultSorted = list(Year = "desc"),
  theme = reactableTheme(
    color = "var(--bs-body-color)",
    backgroundColor = "var(--bs-body-bg)",
    borderColor = "var(--bs-border-color)",
    stripedColor = "rgba(128, 128, 128, 0.1)",
    highlightColor = "rgba(128, 128, 128, 0.15)",
    headerStyle = list(
      borderColor = "var(--bs-border-color)",
      color = "var(--bs-body-color)"
    ),
    paginationStyle = list(color = "var(--bs-body-color)")
  )
)
```
