---
title: "Publications"
site: distill::distill_website
output: 
  distill::distill_article
---

```{css, echo = F}
.fcolumns {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  width: 100%;
  margin: 0 10px
}
.fcolumn1 {
  flex: 10%;
}
.fcolumn2 {
  flex: 90%;
}

.fcolumn3 {
  flex: 15%;
}
.fcolumn4 {
  flex: 80%;
}

.fcolumnspace {
  flex: 5%;
}


d-title {
    display: none;
  }

.feat_img{
  height: auto;
  width: 95%!important;
}

d-article p {
margin-bottom: 0em;
}

tbody th, table.dataTable tbody td {
padding: 5px 10px;
}

thead {    
    display:none;   
}

table.dataTable thead th {
  border-bottom: none !important;
}
table.dataTable.no-footer {
  border-bottom: none !important;
}
article table td {
font-size: 1.06rem;
}
```

```{js, echo = F}

window.onload = function(){
    l=document.links.length;
    for(i = 0; i<l; i++) {
        n = document.links[i].href.indexOf(".pdf");

        if (n > 0){
            document.links[i].setAttribute('target', '_blank');
        }
    }
}

$(document).ready(function(){
	
   // external links to new window
    $('a[href^="http://"]').not('a[href*="https://robcavanaugh.com"]').attr('target','_blank');
    
    // force PDF Files to open in new window
    $('a[href$=".pdf"]').attr('target', '_blank');

  });
```


```{r, include=FALSE}

source("R/cv_printing_functions_website.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1B2gc55CwWn0QidoLk3aqWXFaKGFXqekKV94LVyY7Gug/edit?usp=sharing",  
  pdf_mode = 'false'
)
CV$entries_data$institution[CV$entries_data$institution=="N/A"] <- ""

```

<br> 

```{r, echo = F, layout = "l-body-outset"}
htmltools::tags$h2("Publications")
```

```{r echo = FALSE, layout = "l-body-outset"}
#CV %<>% print_section("publications")

library(magrittr)
library(dplyr)
library(tidyr)
library(stringr)
t = CV$entries_data %>%
  dplyr::filter(section == "publications", in_website == "TRUE") %>%
  dplyr::mutate(start = ifelse(start == "N/A", NA, start)) %>%
  fill(start) %>%
  rowwise() %>%
  mutate(pdf = ifelse(loc == "N/A", "", glue::glue('<a href = "images/{loc}" id="pdflink"><button id="pdfbutton">Author PDF</button></a>')),
         title = markdown::markdownToHTML(text = paste(title, pdf), fragment.only = TRUE)) %>%
  select(Article = title)
 
DT::datatable(t,
              escape = FALSE,
              rownames = FALSE,
              class="compact hover",
              option = list(pageLength = 5, lengthChange = FALSE, searching = FALSE, info = FALSE))

```

```{r, echo = F, layout = "l-body-outset", include = FALSE}
htmltools::tags$h2("Pre-prints")
```

```{r results='asis', echo = FALSE, layout = "l-body-outset", include = FALSE}
# CV %<>% print_section("review") 
```

```{r, echo = F, layout = "l-body-outset"}
htmltools::tags$h3("Selected Presentations")
```

```{r results='asis', echo = FALSE, layout = "l-body-outset"}
CV %<>% print_section("presentations", glue_template = "poster") 
```
