---
title: "Producing reproducibile articles for ASHA journals using Quarto"
description: | 
  This post details the steps for using Quarto to generate a reproducible manuscript that could be submitted without further editing to the ASHA journals. To achieve this goal, we use our recently published manuscript “Reproducibility in small-N treatment research: a tutorial through the lens of aphasiology,” as an example to use Quarto.
date: "`r Sys.Date()`"
author:
  - name: Rob Cavanaugh
  - name: Yina Quique
citation:
  url: https://robcavanaugh.com/posts/
draft: true
preview: preview.png
creative_commons: CC BY
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  markdown: 
    wrap: 72
---

```{css, echo = FALSE}
d-article li p {
    margin-bottom: 0em;
    margin-left: 0;
    padding-left: 0;
}
d-article li {
    margin-bottom: 0em;
    margin-left: 0;
    padding-left: 0;
}
```

\## Method 2: Reproducible manuscript

\- Everything is produced by R scripts within the manuscript

\- overview of what to do

\- reference a separate detailed document as a reference

# Background

Our [research lab](https://lrcl.pitt.edu) at the University of
Pittsburgh has been striving to improve our open science practices over
the last 3-4 years. This has included sharing data and analysis
scripts[^1], using pre-registration prior to analyzing data,[^2] and
generating reproducible figures and results text directly from our
analysis scripts[^3]. We're not perfect, and we've made some mistakes
along the way, but we're doing our best.

[^1]: e.g., <https://osf.io/sfutm/> and <https://osf.io/dxvyj/>

[^2]: <https://osf.io/r687h>

[^3]: Inspired by T.J. Mahr:
    <https://www.tjmahr.com/lists-knitr-secret-weapon/>

One goal we've had for a while is to share a fully reproducible
manuscript - that is, the manuscript, and any tables, figures, and
results can be compiled from the software without further editing. In
this way, the manuscript would be ready in a submission-ready format
directly. The idea behind the fully reproducible manuscript is that not
only are our results fully reproducible, but so is our reporting of
those results.

There are several methods for generating fully reproducible manuscripts
for journals that accept .pdf or LaTeX files for submission. We aimed to
generate a fully reproducible manuscript for the American
Speech-Language and Hearing Association (ASHA) journals, which prefer
Microsoft Word documents in APA-7 format. Specifically, we wanted to
develop a workflow for generating reproducible manuscripts that works
with anyone - including external collaborators who might have little to
no experience with R (our tool of choice).

Our recent publication entitled *Reproducibility in small-N treatment
research: a tutorial using examples from aphasiology* in the special
issue of the Journal of Speech-Language-Hearing Research (JSLHR) focused
on reproducibility. We though we would use this opportunity to try to
submit a fully reproducible manuscript. To generate this manuscript, we
used a new tool from Rstudio, [Quarto](https://quarto.org), which is the
"next generation" of Rmarkdown. This post details our workflow and
reports on some pains with moving towards reproducibility in this way.

# Requirements

For our reproducible manuscript to be successful, we wanted to ensure it
fit within our typical lab workflow. This workflow (1) assumes that at
least one author is completely unfamiliar with R and RMarkdown/Quarto,
(2) assumes that *all* authors prefer to write in a word processor like
Microsoft Word -- where comments, comment threads, and track changes are
non-negotiable, (3) assumes that all data wrangling and statistical
analyses are done in a separate script (at least at the start of the
manuscript) and key elements (clean data, model objects) of the analysis
can be loaded into the manuscript.[^4]

[^4]: We submitted the initial submission using our regular process of
    collaboratively editing a word document, generating the
    tables/figures and results text programmatically in Rmarkdown
    documents, and pasting the results text whole into the manuscript.
    However, the process for the revision is what we would expect to use
    for both had we had our act together the first time.

The manuscript itself needed to be formatted as an APA-7 word document
(for JSLHR), with the following requirements:

-   Double spaced font, times new roman 12pt, continuous line numbers,
    page numbers, 1" margins, APA formatted citations.

-   A title page with specific content (title, authors, disclosures,
    keywords, corresponding author information).

-   Abstract on the second page.

-   Manuscript body pages with "Table/Figure X. about here" to indicate
    table/figure placement.

-   Acknowledgements and funding information between the manuscript body
    and references

-   A list of table and figure captions that comes after the references

-   Tables in .docx or .xlsx format and Figures as .jpg or .png files in
    separate files

-   Changes marked in red on revision (ASHA also allows tracked changes,
    but our preference is to highlight changes in red)

# Workflow

**Initial Submission**

1.  Draft the initial manuscript.
    -   The initial manuscript text could be drafted using your normal
        collaborative process in Microsoft Word, Google Docs, or Quarto.

    -   Use placeholder text for the tables, figures, results values and
        citations (don't use a citation manager in Microsoft Word, we'll
        do that in Quarto).

    -   Generate the tables and figures in APA-7 in dedicated scripts,
        saving the tables as .docx and figures as .png files in your
        manuscript folder.
2.  Create a Quarto docx document and fill out the YAML section and
    abstract
3.  Copy the manuscript text into the Quarto document
4.  Edit the results text to include values from the manuscript using
    inline code
5.  Add references using the RStudio citation add-in (or the {rbbt} R
    package add-in to access Zotero -- an open-source reference manager
6.  Add the figure and table captions at the end of the references
7.  At this point, you should be able to render the document to
    Microsoft Word.
8.  Share the document in Microsoft Word format with collaborators and
    solicit final edits. Incorporate these edits into the Quarto
    document.
9.  Render a final version, and upload all documents for submission.

**Revision:**

1.  Edit the quarto manuscript in Rmarkdown and re-render to word.
2.  Use the "compare documents" feature of Microsoft Word or Google Docs
    to mark changes in the manuscript. Note that you can specify that
    you only want content comparison (comparison that ignores
    formatting, for example) to focus on the changes that require
    attention.
3.  Share edits with collaborators to solicit feedback, incorporate
    feedback back into the Quarto document
4.  Incorporate co-author changes into the quarto document
5.  Re-render to word. Use the "compare documents" feature again.
6.  If desired, change any changes from "compare documents" to red or
    highlighted font (per preference). Otherwise, keep with tracked
    changes.
7.  Re-submit to journal

# Thoughts (strengths & weaknesses)

We think the approach used in this manuscript is a good starting place
for writing reproducible manuscripts for the ASHA journals, but its' not
perfect. It creates additional work for the (probably) first author to
incorporate and format the manuscript within a Quarto document. It's
also unclear how much of an improvement this approach is over our
previous approaches, which were to programmatically generate publication
ready tables, figures, and results text, and then paste the results text
into the paper.

The citation manager used by RStudio/rbbt is one substantial upgrade on
the Microsoft Word /google doc plug-ins, which in our experience, tend
to get bogged down once you add more than 20 citations. In Quarto, the
citation output is generated only until you render the document, which
removes the time the plug-in takes to reformat everything (especially
when you add a citation early on in a paper with many numbered
citations).

There are still limited options for converting Quarto (and RMarkdown) to
Microsoft Word in desired formats. We had used a few less-than-ideal
solutions to resolve some formatting challenges. Having more control
over the output document from the YAML header would be great. We're
pretty sure there are solutions to this, but probably beyond our
expertise. The {papaja} R package can produce APA-formatted word
documents, but we haven't found a way to generate a word document from
papaja that doesn't need a few manual tweaks before submission.

What we really need to make Quarto the future of reproducible
manuscripts (in any format) is additional functionality to programs like
[Rstudio Cloud](Rstudio.cloud), where multiple collaborators can edit
the same document simultaneously. The ability to add comments (and
comment threads) like in Microsoft Word / Google Docs and additional
improvements to the UI to make it appear close to standard word
processors will make the programs more accessible to collaborators who
don't know how to use R (and so that they don't need to learn and R!).
For example, being able to toggle inline code to show the result in the
editor, and the ability to lock

Anyways, for those of you still reading this post, the following section
describes how to format a Quarto document to render an ASHA-journal
compliant manuscript.

# Formatting a Quarto Document

For the reproducible manuscript, we recommend writing in the RStudio
Visual mode, which has some keyboard shortcuts and options users of
Microsoft Word / Google Docs will be familiar with (e.g., cmd + b
generates bold text). It also includes menu options to insert citations
and equations.

## 1. YAML Header

The top of each quarto document begins with a "YAML header" enclosed by
`---` which indicates the document settings and some pre-filled data.
Note that YAML headers are case sensitive and sensitive to whitepace.
Quarto comes with auto-complete YAML headers, which I encourage everyone
to use. The YMAL header for our reproducible word document looks like
this:

    ---
    title: "Reproducibility in small-N treatment research: a tutorial using examples from aphasiology"

    author: |
      Robert Cavanaugh,^1,2^ Yina M. Quique,^3^ Alexander M. Swiderski,^1,2,4^
      Lydia Kallhoff,^5^ Lauren Terhorst,^6^ Julie Wambaugh,^5^
      William D. Hula,^2,1^ William S. Evans^1^

    # There's no affiliation distinction in the word doc, so using abstract to fill the info 
    # Abstract is included manually below. This also ensures abstract is on a separate page.
    abstract: |
      1.    University of Pittsburgh, Department of Communication Sciences and Disorders
      2.    VA Pittsburgh Healthcare System, Audiology and Speech Pathology Program
      3.    Center for Education in Health Sciences, Northwestern University & Shirley Ryan Ability Lab
      4.    Carnegie Mellon University, Center for Neural Basis of Cognition
      5.    University of Utah, Department of Communication Sciences and Disorders
      6.    University of Pittsburgh, Department of Occupational Therapy

    format:
      docx:
         reference-doc: "templates-data/custom-reference-doc.docx"
         pandoc_args: ["-Fpandoc-crossref"]
    bibliography: "citations.bib"
    csl: apa.csl
    ---

### YAML breakdown:

-   `title:` is the title of the article

-   `author:` is the manuscript authorship. Affiliation numbers are
    surrounded by `^` without any spaces. Users of other rmarkdown
    packages like {papaja} undoubtedly notice that author and
    affiliation are not split up. If there's a way to add affiliations
    in this way to .docx output, I'd love to hear it, but this seemed
    like a simple and reasonable solution for now.

-   `abstract:` As indicated in the comments, I'm actually using the
    `abstract:` YAML field to include the affiliations for the article.
    The `|` indicates that the affiliation text will start on an
    indented line below. Use the abstract field for the affiliations
    ensures the abstract started on a new page, and that the
    affiliations followed the author field. Again, if there's a way to
    add an affiliation field for .docx output, I'd love to add it.

-   `format:` specifies that the output of the document will be a word
    document and contains two **key** arguments. First, it specifies the
    word template used to format the document. The `pandoc_args:` is
    needed for numbering equations used in our manuscript (but as far as
    I can tell is not necessary otherwise).

-   `bibliography:` indicates where the bibliography file is stored

-   `csl:` indicates the file used for formatting citations. I'm using
    the APA-7 file which I found [here](google.com)

### More on `reference_doc`

The reference document specified here contains most of the changes that
I needed to make to obtain the correct formatting. Quarto has great
documentation on using the reference documents
(<https://quarto.org/docs/output-formats/ms-word-templates.html>). I
made the following changes to the default reference document from
pandoc. Feel free to modify my document (found here) or the original
pandoc template.

-   All styles changed to times new roman

-   All styles changed to 12pt font, black

-   All styles (except some headers) changed to double-spacing

-   Line numbers added

-   Page numbers added

-   Hanging indent added to reference style

-   Code formatting simplified with desired font-size and coloring

-   Heading 5 was centered so that I could use `#####` to format level-5
    headers as centered text for the table/figure position indicators
    ("Figure 1 about here").

-   An additional style "noIndentParagraph" was added (see below).

## 2. Title page & Abstract

-   To finish the title page, we included the following below the YAML
    in the beginning of the document:

> \<br\>
>
> The authors have no disclosures.\\
>
> Key words: aphasia treatment reproducibility replication
>
> \<br\>
>
> Corresponding Author:\\
>
> Robert Cavanaugh M.S. CCC-SLP\\
>
> rob.cavanaugh\\\@pitt.edu
>
> \\newpage

-   \< br \> adds a line break to add some spacing after the
    affiliations and after the keywords.

-   \\ after a line indicates a new line break

-   \\\@ escapes the \@ character which is used for citations in Quarto

-   \\ newpage creates a page break so that the abstract goes on a new
    page

## 3. Manuscript Text

The manuscript text is regular markdown text, using headers, bold,
italics, footnotes, and equations as we normally would. Our word
template will format the text pretty close to APA-7 formatting.

We did need to include a minor customization to specify that a paragraph
should not be indented manually (this was used for the abstract, and
table/figure captions). To do this, we wrapped any paragraphs where no
indent was desired in "fenced-div" like so:

    ::: {custom-style="noIndentParagraph"}

    Non-indented paragraph goes here

    :::

## 4. Citations

Citations can be added to the text in a few different ways. You can use
the R-studio citation add-in (Insert -\> citation) which allows you to
pull citations from a number of different sources. If you want to access
Zotero directly, you can also use the {rbbt} R package. Because we want
to add a list of our table and figure captions after the references
section, we also need to tell Quarto where to insert the references.
This can be done by creating an element with `#refs` after the
acknowledgments section. We don't need to put anything inside this
element.

    ::: {#refs}
    :::

![Options for inserting citations using the RStudio citation
add-in](images/citations.png)

## 5. Tables

There are several ways of making APA-style word tables in R. We used the
[flextable package](https://ardata-fr.github.io/flextable-book/) because
it was easiest to generate tables in the format we wanted. For example,
one table in the manuscript included the first five rows of the data.
Here's an example of the code used to produce this table.

```{r, eval = FALSE}
library(officer)
library(flextable)
# create the flextable
t2 <- 
  head(df, 5) %>%
  flextable(cwidth = 0.9) %>%
  set_caption("Table 2. The first 5 rows of data") %>%
  autofit()

# read in a blank template with the correct formatting
doc <- read_docx(here("manuscript", "templates-data", "template_lnd.docx"))
# add the table to the document
doc <- body_add_flextable(doc, value = t2)
# filename within the path we want
fileout <- here("manuscript", "tables-figures", "table2.docx") 
# Save
print(doc, target = fileout)
```

The options for generating figures in image format in R are wide
ranging. Because the ASHA journals only require a separate image file
(.png, .jpg for example), we'll leave it up to the reader to select
their preferred plotting package. We used ggplot2.
