---
title: "Rob Cavanaugh's CV"
author: Rob Cavanaugh
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: false
output:
  pagedown::html_resume:
    css: ['boring_cv.css']
    self_contained: true
---

```{r, include=FALSE}

knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(datadrivencv)
library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1B2gc55CwWn0QidoLk3aqWXFaKGFXqekKV94LVyY7Gug/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta charset="utf-8">
<script src="https://kit.fontawesome.com/bee4f5cfa6.js" crossorigin="anonymous"></script>
<!-- <link rel="preconnect" href="https://fonts.googleapis.com"> -->
<!-- <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> -->
<!-- <link href="https://fonts.googleapis.com/css2?family=Tinos&display=swap" rel="stylesheet"> -->

```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```



Main
================================================================================

Robert B. Cavanaugh {#title}
--------------------------------------------------------------------------------
<hr>
<!-- <div style="font-size:14px;padding:0px;margin:0px;">M.S. CCC-SLP</div> -->
<div id="intro">
M.S. CCC-SLP `r knitr::asis_output("\U00B7")` Ph.D Candidate, University of Pittsburgh<br>
<!-- <span style="font-size:0.9rem;">School of Health and Rehabilitation Sciences, University of Pittsburgh</span>   -->
`r fontawesome::fa("envelope")` rob.cavanaugh@pitt.edu `r knitr::asis_output("\U00B7")`
`r fontawesome::fa("globe")` [robcavanaugh.com](https://robcavanaugh.com) `r knitr::asis_output("\U00B7")`  
`r fontawesome::fa("orcid")` [orcidID](https://orcid.org/0000-0002-2114-6565) `r knitr::asis_output("\U00B7")` 
`r fontawesome::fa("github")` [Github](https://github.com/rbcavanaugh) `r knitr::asis_output("\U00B7")` 
`r fontawesome::fa("twitter")` [Twitter](https://twitter.com/Littlejohnsband)  
<em style="font-size:0.8rem;">Last updated on `r Sys.Date()`</em>
</div>

<hr>

<!-- <div style="font-size:0.9rem;"> -->
<!-- ```{r} -->
<!-- # Note the special double pipe so we modify the CV object in place -->
<!-- CV %<>% print_text_block("intro")  -->
<!-- ``` -->
<!-- </div> -->

I'm a PhD candidate and ASHA-certified speech-language pathologist. My research aims to improve the effectiveness and clinical implementation of aphasia rehabilitation services from two perspectives: (1) specifying the active ingredients of aphasia treatments and (2) developing technology-based tools to accelerate the clinical implementation of aphasia research. To achieve these goals, my research combines training in aphasia treatment theory, quantitative methods and statistical programming, implementation science, and my clinical experiences as a speech-language pathologist. I’m also passionate about sharing and promoting quantitative methods and open science practices within the field of communication sciences and disorders. 

Education {data-icon=graduation-cap }
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



<!-- Clinical Experience {data-icon=hospital data-concise=true} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('clinical') -->
<!-- ``` -->

Professional Experience {data-icon=briefcase data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('positions', glue_template = "positions")
```

Grant Support {data-icon=pen-alt}
--------------------------------------------------------------------------------


```{r class.source="pubs"}
CV %<>% print_section('grants', glue_template = "grant")
```


Scholarships and Awards {data-icon=award}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('honors', glue_template = "other")
```


Publications {data-icon=file-alt}
--------------------------------------------------------------------------------


```{r class.source="pubs"}
CV %<>% print_section('publications', glue_template = "citation")
```

<!-- Publications Under Review & In Revision {data-icon=chalkboard-teacher} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('review', glue_template = "citation") -->
<!-- ``` -->


Refereed Presentations {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('presentations', glue_template = "citation")
```

Software & Technology {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('software', glue_template = "other")
```

Teaching {data-icon=university}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching', glue_template = "other")
```

Professional Memberships {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('certs', glue_template = "other")
```

Service {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('service', glue_template = "other")
```

Media {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('media', glue_template = "other")
```
